import { lstat, readFile } from "node:fs/promises";
import { join } from "node:path";

import {
  ExitCode,
  PaperbotError,
  type ScanManifest,
  type ScannedFile,
} from "@prodxiv/paperbot-core";

import { classifySourcePath } from "./classification.ts";
import { inspectGitRepository } from "./git.ts";

const MAX_SOURCE_BYTES = 1024 * 1024;

const DEFAULT_EXCLUSIONS = [
  "**/.env",
  "**/.env.*",
  "**/.npmrc",
  "**/.pypirc",
  "**/.aws/**",
  "**/.secrets/**",
  "**/credentials",
  "**/credentials.*",
  "**/credentials/**",
  "**/secret",
  "**/secret.*",
  "**/secrets",
  "**/secrets.*",
  "**/secrets/**",
  "**/*.pem",
  "**/*.key",
  "**/*.p12",
  "**/*.pfx",
  "**/id_dsa*",
  "**/id_ecdsa*",
  "**/id_ed25519*",
  "**/id_rsa*",
  "**/*.db",
  "**/*.sqlite",
  "**/*.sqlite3",
  "**/backup/**",
  "**/backups/**",
  "**/user_data/**",
  "**/userdata/**",
  "**/uploads/**",
  "**/node_modules/**",
  "**/vendor/**",
  "**/target/**",
  "**/dist/**",
  "**/build/**",
  "**/out/**",
  "**/coverage/**",
  "**/.astro/**",
  "**/.next/**",
  "**/.turbo/**",
  "**/gen/**",
  "**/generated/**",
] as const;

const GENERATED_MARKERS = [
  "do not edit manually",
  "do not edit this file",
  "@generated",
  "code generated",
];
const SECRET_MARKERS = [
  "-----begin private key-----",
  "-----begin rsa private key-----",
  "-----begin ec private key-----",
  "-----begin openssh private key-----",
];

export interface ScanOptions {
  exclusions?: string[];
  inclusions?: string[];
}

export type SkipReason =
  "excluded" | "generated" | "binary" | "oversized" | "symlink" | "unsupported";

export interface ScanResult {
  manifest: ScanManifest;
  repository_path: string;
  discovered_file_count: number;
  skipped_file_counts: Record<SkipReason, number>;
}

export async function scanRepository(
  repositoryPath: string,
  options: ScanOptions = {},
): Promise<ScanResult> {
  const repository = await inspectGitRepository(repositoryPath);
  const defaultExclusionGlobs = DEFAULT_EXCLUSIONS.map(
    (pattern) => new Bun.Glob(pattern),
  );
  const explicitExclusionGlobs = (options.exclusions ?? []).map(
    (pattern) => new Bun.Glob(pattern),
  );
  const inclusionGlobs = (options.inclusions ?? []).map(
    (pattern) => new Bun.Glob(pattern),
  );
  const skipped_file_counts = emptySkipCounts();
  const files: ScannedFile[] = [];

  for (const path of repository.files) {
    const normalizedPath = path.toLowerCase();
    const explicitlyExcluded = explicitExclusionGlobs.some((glob) =>
      glob.match(path),
    );
    const excludedByDefault = defaultExclusionGlobs.some((glob) =>
      glob.match(normalizedPath),
    );
    const explicitlyIncluded = inclusionGlobs.some((glob) => glob.match(path));
    if (explicitlyExcluded || (excludedByDefault && !explicitlyIncluded)) {
      skipped_file_counts.excluded += 1;
      continue;
    }

    const file_type = classifySourcePath(path);
    if (file_type === undefined) {
      skipped_file_counts.unsupported += 1;
      continue;
    }

    const absolutePath = join(repository.root_path, path);
    let metadata;
    try {
      metadata = await lstat(absolutePath);
    } catch {
      throw new PaperbotError(
        `could not inspect repository file: ${path}`,
        ExitCode.scan,
      );
    }
    if (metadata.isSymbolicLink()) {
      skipped_file_counts.symlink += 1;
      continue;
    }
    if (!metadata.isFile()) {
      skipped_file_counts.unsupported += 1;
      continue;
    }
    if (metadata.size > MAX_SOURCE_BYTES) {
      skipped_file_counts.oversized += 1;
      continue;
    }

    let content: Buffer;
    try {
      content = await readFile(absolutePath);
    } catch {
      throw new PaperbotError(
        `could not read repository file: ${path}`,
        ExitCode.scan,
      );
    }
    if (content.includes(0)) {
      skipped_file_counts.binary += 1;
      continue;
    }

    const sample = content.subarray(0, 4096).toString("utf8").toLowerCase();
    if (GENERATED_MARKERS.some((marker) => sample.includes(marker))) {
      skipped_file_counts.generated += 1;
      continue;
    }
    if (SECRET_MARKERS.some((marker) => sample.includes(marker))) {
      skipped_file_counts.excluded += 1;
      continue;
    }

    files.push({
      path,
      file_type,
    });
  }

  const manifest: ScanManifest = {
    schema_version: "1",
    repository: {
      revision: repository.revision,
      is_dirty: repository.is_dirty,
      ...(repository.source_url === undefined
        ? {}
        : { source_url: repository.source_url }),
    },
    files,
  };

  return {
    manifest,
    repository_path: repository.scan_path,
    discovered_file_count: repository.files.length,
    skipped_file_counts,
  };
}

function emptySkipCounts(): Record<SkipReason, number> {
  return {
    excluded: 0,
    generated: 0,
    binary: 0,
    oversized: 0,
    symlink: 0,
    unsupported: 0,
  };
}
