import { lstat, readFile } from "node:fs/promises";
import { basename, join } from "node:path";

import { ExitCode, PaperbotError } from "./errors.ts";
import { inspectGitRepository } from "./git.ts";
import type {
  ScanFileType,
  ScanManifest,
  ScannedFile,
} from "./scan-manifest.ts";

const MAX_SOURCE_BYTES = 1024 * 1024;

const DEFAULT_EXCLUSIONS = [
  "**/.env",
  "**/.env.*",
  "**/.npmrc",
  "**/.pypirc",
  "**/.aws/**",
  "**/.secrets/**",
  "**/credentials",
  "**/credentials.*",
  "**/credentials/**",
  "**/secret",
  "**/secret.*",
  "**/secrets",
  "**/secrets.*",
  "**/secrets/**",
  "**/*.pem",
  "**/*.key",
  "**/*.p12",
  "**/*.pfx",
  "**/id_dsa*",
  "**/id_ecdsa*",
  "**/id_ed25519*",
  "**/id_rsa*",
  "**/*.db",
  "**/*.sqlite",
  "**/*.sqlite3",
  "**/backup/**",
  "**/backups/**",
  "**/user_data/**",
  "**/userdata/**",
  "**/uploads/**",
  "**/node_modules/**",
  "**/vendor/**",
  "**/target/**",
  "**/dist/**",
  "**/build/**",
  "**/out/**",
  "**/coverage/**",
  "**/.astro/**",
  "**/.next/**",
  "**/.turbo/**",
  "**/gen/**",
  "**/generated/**",
] as const;

const DOCUMENTATION_EXTENSIONS = new Set([".adoc", ".md", ".mdx", ".rst"]);
const SOURCE_EXTENSIONS = new Set([
  ".astro",
  ".bash",
  ".c",
  ".cc",
  ".cpp",
  ".cs",
  ".css",
  ".go",
  ".graphql",
  ".h",
  ".hpp",
  ".html",
  ".java",
  ".js",
  ".jsx",
  ".kt",
  ".kts",
  ".php",
  ".proto",
  ".py",
  ".rb",
  ".rs",
  ".scss",
  ".sh",
  ".sql",
  ".svelte",
  ".swift",
  ".ts",
  ".tsx",
  ".vue",
  ".zsh",
]);
const CONFIGURATION_EXTENSIONS = new Set([
  ".conf",
  ".ini",
  ".json",
  ".properties",
  ".toml",
  ".xml",
  ".yaml",
  ".yml",
]);
const MANIFEST_FILENAMES = new Set([
  "bun.lock",
  "cargo.lock",
  "cargo.toml",
  "composer.json",
  "composer.lock",
  "deno.json",
  "deno.jsonc",
  "gemfile",
  "gemfile.lock",
  "go.mod",
  "go.sum",
  "package-lock.json",
  "package.json",
  "pnpm-lock.yaml",
  "poetry.lock",
  "pyproject.toml",
  "requirements.txt",
  "uv.lock",
  "yarn.lock",
]);
const CONFIGURATION_FILENAMES = new Set([
  ".dockerignore",
  ".editorconfig",
  ".gitattributes",
  ".gitignore",
  "containerfile",
  "dockerfile",
  "justfile",
  "makefile",
]);
const DOCUMENTATION_FILENAMES = new Set([
  "agents.md",
  "changelog",
  "changelog.md",
  "contributing.md",
  "license",
  "license.md",
  "readme",
  "readme.md",
]);
const GENERATED_MARKERS = [
  "do not edit manually",
  "do not edit this file",
  "@generated",
  "code generated",
];
const SECRET_MARKERS = [
  "-----begin private key-----",
  "-----begin rsa private key-----",
  "-----begin ec private key-----",
  "-----begin openssh private key-----",
];

export interface ScanOptions {
  exclusions?: string[];
  inclusions?: string[];
}

export type SkipReason =
  "excluded" | "generated" | "binary" | "oversized" | "symlink" | "unsupported";

export interface ScanResult {
  manifest: ScanManifest;
  repository_path: string;
  discovered_file_count: number;
  skipped_file_counts: Record<SkipReason, number>;
}

export async function scanRepository(
  repositoryPath: string,
  options: ScanOptions = {},
): Promise<ScanResult> {
  const repository = await inspectGitRepository(repositoryPath);
  const defaultExclusionGlobs = DEFAULT_EXCLUSIONS.map(
    (pattern) => new Bun.Glob(pattern),
  );
  const explicitExclusionGlobs = (options.exclusions ?? []).map(
    (pattern) => new Bun.Glob(pattern),
  );
  const inclusionGlobs = (options.inclusions ?? []).map(
    (pattern) => new Bun.Glob(pattern),
  );
  const skipped_file_counts = emptySkipCounts();
  const files: ScannedFile[] = [];

  for (const path of repository.files) {
    const normalizedPath = path.toLowerCase();
    const explicitlyExcluded = explicitExclusionGlobs.some((glob) =>
      glob.match(path),
    );
    const excludedByDefault = defaultExclusionGlobs.some((glob) =>
      glob.match(normalizedPath),
    );
    const explicitlyIncluded = inclusionGlobs.some((glob) => glob.match(path));
    if (explicitlyExcluded || (excludedByDefault && !explicitlyIncluded)) {
      skipped_file_counts.excluded += 1;
      continue;
    }

    const file_type = classifyFile(path);
    if (file_type === undefined) {
      skipped_file_counts.unsupported += 1;
      continue;
    }

    const absolutePath = join(repository.root_path, path);
    let metadata;
    try {
      metadata = await lstat(absolutePath);
    } catch {
      throw new PaperbotError(
        `could not inspect repository file: ${path}`,
        ExitCode.scan,
      );
    }
    if (metadata.isSymbolicLink()) {
      skipped_file_counts.symlink += 1;
      continue;
    }
    if (!metadata.isFile()) {
      skipped_file_counts.unsupported += 1;
      continue;
    }
    if (metadata.size > MAX_SOURCE_BYTES) {
      skipped_file_counts.oversized += 1;
      continue;
    }

    let content: Buffer;
    try {
      content = await readFile(absolutePath);
    } catch {
      throw new PaperbotError(
        `could not read repository file: ${path}`,
        ExitCode.scan,
      );
    }
    if (content.includes(0)) {
      skipped_file_counts.binary += 1;
      continue;
    }

    const sample = content.subarray(0, 4096).toString("utf8").toLowerCase();
    if (GENERATED_MARKERS.some((marker) => sample.includes(marker))) {
      skipped_file_counts.generated += 1;
      continue;
    }
    if (SECRET_MARKERS.some((marker) => sample.includes(marker))) {
      skipped_file_counts.excluded += 1;
      continue;
    }

    files.push({
      path,
      file_type,
    });
  }

  const manifest: ScanManifest = {
    schema_version: "1",
    repository: {
      revision: repository.revision,
      is_dirty: repository.is_dirty,
      ...(repository.source_url === undefined
        ? {}
        : { source_url: repository.source_url }),
    },
    files,
  };

  return {
    manifest,
    repository_path: repository.scan_path,
    discovered_file_count: repository.files.length,
    skipped_file_counts,
  };
}

function classifyFile(path: string): ScanFileType | undefined {
  const lowerPath = path.toLowerCase();
  const filename = basename(lowerPath);
  const extensionIndex = filename.lastIndexOf(".");
  const extension = extensionIndex === -1 ? "" : filename.slice(extensionIndex);
  const segments = lowerPath.split("/");

  if (
    segments.some(
      (segment) =>
        segment === "bench" ||
        segment === "benches" ||
        segment === "benchmarks",
    ) ||
    /(?:^|[._-])bench(?:mark)?(?:[._-]|$)/.test(filename)
  ) {
    return "benchmark";
  }
  if (
    segments.some(
      (segment) =>
        segment === "test" || segment === "tests" || segment === "__tests__",
    ) ||
    /(?:^|[._-])(?:spec|test)(?:[._-]|$)/.test(filename)
  ) {
    return "test";
  }
  if (
    DOCUMENTATION_FILENAMES.has(filename) ||
    DOCUMENTATION_EXTENSIONS.has(extension) ||
    segments.includes("docs")
  ) {
    return "documentation";
  }
  if (MANIFEST_FILENAMES.has(filename)) {
    return "manifest";
  }
  if (
    CONFIGURATION_FILENAMES.has(filename) ||
    filename === ".env" ||
    filename.startsWith(".env.") ||
    CONFIGURATION_EXTENSIONS.has(extension) ||
    segments.includes(".github") ||
    segments.includes("config")
  ) {
    return "configuration";
  }
  if (SOURCE_EXTENSIONS.has(extension)) {
    return "source_code";
  }
  return undefined;
}

function emptySkipCounts(): Record<SkipReason, number> {
  return {
    excluded: 0,
    generated: 0,
    binary: 0,
    oversized: 0,
    symlink: 0,
    unsupported: 0,
  };
}
